
package:
  name: cadquery-arkon
  version:  {{ environ.get('PACKAGE_VERSION') }}

source:
  path: ../..

build:

  noarch: python

  string: {{ 'py'+environ.get('PYTHON_VERSION')}}

  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:

  build:
    - python {{ environ.get('PYTHON_VERSION') }}.*
    - setuptools

  run:
    - python {{ environ.get('PYTHON_VERSION') }}.*
    - pyparsing
    - cadquery-pyocct

about:

summary: CQ Arkon (core app)
